/*
 * This source file was generated by the Gradle 'init' task
 */
package xyz.amycute;

import com.hypixel.hytale.server.core.plugin.JavaPlugin;
import com.hypixel.hytale.server.core.plugin.JavaPluginInit;
import com.hypixel.hytale.logger.HytaleLogger;
import xyz.amycute.energy.EnergyModule;

/**
 * Main plugin class.
 */
public class HytaleEnergyApi extends JavaPlugin {

    private static HytaleEnergyApi instance;
    private static final HytaleLogger logger = HytaleLogger.forEnclosingClass();

    /**
     * Constructor - Called when plugin is loaded.
     * Ensures that the JavaPluginInit reference is not null.
     *
     * @param init the plugin initialization object (must not be null)
     * @throws NullPointerException if init is null
     */
    public HytaleEnergyApi(JavaPluginInit init)
    {
        super(init);
        instance = this;
        logger.atInfo().log("Plugin loaded!");
    }

    @Override
    public void setup()
    {
        logger.atInfo().log("Plugin enabled!");
        EnergyModule.init(getEntityStoreRegistry());
    }


    @Override
    public void shutdown()
    {
        logger.atInfo().log("Plugin disabled!");
    }


    public static HytaleEnergyApi getInstance() {
        return instance;
    }
}
